feat: добавлена авторизация Yandex OAuth
DVAA-team/galaga pull request #40
Opened 2022-08-22 11:04 UTC by xczdenis

2022-08-22 12:22 UTC, AntLer-24rus requested changes
Здорово! Стало сильно круче что можно не фигачить логин и пароль каждый раз! Молодец!

2022-08-22 12:22 UTC, AntLer-24rus commented on src/services/yandexOAuthService.ts
> +  private _redirectUri = 'http://localhost:3000';
Тут бы завязаться как-то на baseURL сайта, когда задеплоимся никакого локалхота уже не будет, да и порт скорее вссего поменяется. Как варант использовать `window.location.origin`

2022-08-22 12:22 UTC, AntLer-24rus commented on src/api/types.ts
> +  code: 'string';
Думаю тут кавычки лишние

2022-08-22 12:22 UTC, AntLer-24rus commented on src/pages/Home/Home.tsx
> +      const authorizationCode = searchParams.get('code');
Тут бы неплохо этот код удалять из адресной строки, иначе если страницу обновишь, пишет что пользователь уже в сети

2022-08-22 12:22 UTC, AntLer-24rus commented on src/components/YandexLogin/YandexLogin.tsx
> +  return <a href={targetUrl}>Войти через Яндекс</a>;
Может возьмем за основу дизайна одну из предложенных кнопок [Дока Яндекса](https://yandex.ru/dev/id/doc/dg/api-id/reference/buttons.html#buttons__basic)

2022-08-22 12:22 UTC, AntLer-24rus commented on src/pages/Home/Home.tsx
> +            redirectUri: 'http://localhost:3000',
Тут может рассогласование получится в файлом `yandexOAuthService.ts` а менно [строка](https://github.com/DVAA-team/galaga/blob/b6cf0e1eec089cc189b67f28dc047568c208ab42/src/services/yandexOAuthService.ts#L38)

2022-08-22 12:24 UTC, AntLer-24rus commented
![](https://github.trello.services/images/mini-trello-icon.png) [OAuth-авторизация](https://trello.com/c/XRZCdE2Y/59-oauth-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F)

2022-08-22 14:14 UTC, axperien approved these changes

2022-08-23 07:28 UTC, AntLer-24rus approved these changes
Все круто! =)

2022-08-23 07:29 UTC, merged