feat: добавлены хедер/навигация/главная страница
DVAA-team/galaga pull request #45
Opened 2022-09-02 11:41 UTC by axperien

2022-09-02 11:42 UTC, axperien commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить навигацию (лэйауты) (см. комменты)](https://trello.com/c/6lJCCyqv/62-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D1%8E-%D0%BB%D1%8D%D0%B9%D0%B0%D1%83%D1%82%D1%8B-%D1%81%D0%BC-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D1%8B)

2022-09-02 12:08 UTC, bestia21v commented on src/components/BackLink/BackLink.tsx
> +      onClick={() => navigate('/')}
Все-таки решил не делать с -1?)

2022-09-02 12:14 UTC, axperien commented on src/components/BackLink/BackLink.tsx
> +      onClick={() => navigate('/')}
тьфу, забыл про это))) сейчас добавлю флаг

2022-09-02 12:44 UTC, axperien commented on src/components/BackLink/BackLink.tsx
> +      onClick={() => navigate('/')}
в общем сделал коммит. -1 делает тоже самое что history.back(). Меня такая реализация всегда бесит, т.к. если путь пользователя не последовательный, то возврат идет такой же, тем более в любом браузере есть нативная кнопка "Назад". В моем решении идет возврат на '../', родительский роут, если он существует. Если сделать для всех ../, то у роутов которые имеют детей - это не сработает. Поэтому добавлена проверка и подставляется либо '../', либо '/'

2022-09-03 05:07 UTC, AntLer-24rus requested changes
Все круто! Выглядит 🔥🔥🔥🔥 Большая работа проделанна!! 💪💪

Расскажи, а почему не наст делать компоненты `MainLayout` и `Header` в корне приложения а решил вставить их в каждую отдельную страницу? 🙈🙈

P.S. Оставил сообшение как порешать с типами 😁😁

2022-09-03 05:07 UTC, AntLer-24rus commented on src/components/Navigation/Navigation.tsx
> +    isActive ? `${styles.link} ${styles['link-active']}` : styles.link;
```diff
-import { NavLink } from 'react-router-dom';
+import { NavLink, NavLinkProps } from 'react-router-dom';
//...
-const getLinkClassName = ({ isActive }: any) =>
+const getLinkClassName: NavLinkProps['className'] = ({ isActive }) =>
```

2022-09-05 05:59 UTC, axperien commented on src/components/Navigation/Navigation.tsx
> +    isActive ? `${styles.link} ${styles['link-active']}` : styles.link;
> 

Решил разбить для большей гибкости, например на любой странице можно указать нужные пропсы хедеру (например заголовок) или вообще его не выводить. В корне он будет неизменяемым для всех страниц. В таком случае только в компоненте хедера делать условия, относительно роута в котором он подключается. Но согласен есть неудобства в использовании. Можно обсудить как лучше) 

Спасибо за подсказку, NavLinkProps я пробовал использовать, но опять забыл про квадратные скобки))))

2022-09-05 07:56 UTC, AntLer-24rus approved these changes

2022-09-05 08:50 UTC, axperien commented
![](https://github.trello.services/images/mini-trello-icon.png) [сделать гарды](https://trello.com/c/FBlKvktn/63-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B3%D0%B0%D1%80%D0%B4%D1%8B)

2022-09-05 09:25 UTC, merged