feat: добавлено API для leaderbord
DVAA-team/galaga pull request #60
Opened 2022-09-20 13:11 UTC by xczdenis

2022-09-20 13:54 UTC, bestia21v reviewed
Денис, крутая работа) Классно, что заложился на будущие доработки) Оставил пару минорных замечаний)

2022-09-20 13:54 UTC, bestia21v commented on src/database/controllers/leaderboardController.ts
> +    order: [['score', 'DESC']],
Можем тут еще лимит добавить?) нам же по факту нужны только первые 3 лидера?)

2022-09-20 13:54 UTC, bestia21v commented on src/pages/Game/Game.tsx
> +        leaderboardService.addToLeaderboard({ score: newScore });
Получается, что мы все скоры хранить будем?)
прикольно будет в дальнейшем сделать историю скоров пользователя)

2022-09-20 13:54 UTC, bestia21v commented on src/pages/Leaderboard/Leaderboard.tsx
> +        const firstThreeLeaders = leaders.splice(0, 3);
а если лидера только 2?) все свалится в ошибку?)

2022-09-20 13:54 UTC, bestia21v commented on src/pages/Leaderboard/components/UserOnPedestal/UserOnPedestal.tsx
> +  const [avatar, setAvatar] = useState<Blob>();
Эту логику с аватаром можно вынести в отдельный кастомный хук)

2022-09-20 13:56 UTC, xczdenis commented on src/database/controllers/leaderboardController.ts
> +    order: [['score', 'DESC']],
не совсем - первые три выводятся на пьедестал, а все остальные просто в список ниже

2022-09-20 14:13 UTC, xczdenis commented on src/pages/Game/Game.tsx
> +        leaderboardService.addToLeaderboard({ score: newScore });
не совсем) сделано как по задумке яндекса - у одного юзера может быть только 1 запись на лидерборде. Она постоянно обновляется

2022-09-20 14:14 UTC, axperien commented
Круто! 💣
Но у меня результат перезаписывается, если даже он ниже лучшего)
И я бы добавил проверку на наличие лидеров, чтобы не выглядела страничка пустой, если вообще никаких результатов нет, либо например только 3 всего

2022-09-20 14:15 UTC, xczdenis commented on src/pages/Leaderboard/Leaderboard.tsx
> +        const firstThreeLeaders = leaders.splice(0, 3);
нет) проверено если даже 1)

2022-09-21 09:59 UTC, AntLer-24rus requested changes
Круто! 🔥 Как же хорошо что ты решил написать свое API это еще ближе двигает нас к собственной авторизации и отвязке от yandex API. Оставил пару комментов! Супер проделанная работа!

2022-09-21 09:59 UTC, AntLer-24rus commented on src/pages/Leaderboard/components/UserOnPedestal/UserOnPedestal.tsx
> +        <p>это место вакантно</p>
Крутяк! 🔥

2022-09-21 09:59 UTC, AntLer-24rus commented on src/server/routes/api/index.ts
>  } from '@/database/models';
У тебя настроена сортировка импортов? Это JetBrains IDE?

2022-09-21 09:59 UTC, AntLer-24rus commented on src/services/leaderboardService.ts
> +              notifySuccess('Круто! У тебя по прежнем серебро!');
буковка `у` пропала... Распространяется это зараза по потере буков 😁

2022-09-22 14:28 UTC, axperien approved these changes

2022-09-22 16:19 UTC, merged